version: '3.8'
networks:
  gulinet:
    name: gulinet
services:
  gulimall-product:
    image: gulimall-product:0.0.1-SNAPSHOT
    deploy:
      resources:
        limits:
          memory: "${APP_MEMORY_LIMIT}"
    container_name: gulimall-product
    environment:
      - "SERVICE_IGNORE=true"
      - "JAVA_TOOL_OPTIONS=${APP_JVM_FLAGS}"
    networks:
      - gulinet
    ports:
      - "${HOST_IP}:${GULIMALL_PRODUCT_PORT}:80"
#      - "${DEBUG_HOST_IP}:${GULIMALL_PRODUCT_DEBUG_PORT}:5005"
  gulimall-coupon:
    image: gulimall-coupon:0.0.1-SNAPSHOT
    deploy:
      resources:
        limits:
          memory: "${APP_MEMORY_LIMIT}"
    container_name: gulimall-coupon
    environment:
      - "SERVICE_IGNORE=true"
      - "JAVA_TOOL_OPTIONS=${APP_JVM_FLAGS}"
    networks:
      - gulinet
    ports:
      - "${HOST_IP}:${GULIMALL_COUPON_PORT}:80"
#      - "${DEBUG_HOST_IP}:${GULIMALL_COUPON_DEBUG_PORT}:5005"
  gulimall-order:
    image: gulimall-order:0.0.1-SNAPSHOT
    deploy:
      resources:
        limits:
          memory: "${APP_MEMORY_LIMIT}"
    container_name: gulimall-order
    environment:
      - "SERVICE_IGNORE=true"
      - "JAVA_TOOL_OPTIONS=${APP_JVM_FLAGS}"
    networks:
      - gulinet
    ports:
      - "${HOST_IP}:${GULIMALL_ORDER_PORT}:80"
#      - "${DEBUG_HOST_IP}:${GULIMALL_ORDER_DEBUG_PORT}:5005"
  gulimall-ware:
    image: gulimall-ware:0.0.1-SNAPSHOT
    deploy:
      resources:
        limits:
          memory: "${APP_MEMORY_LIMIT}"
    container_name: gulimall-ware
    environment:
      - "SERVICE_IGNORE=true"
      - "JAVA_TOOL_OPTIONS=${APP_JVM_FLAGS}"
    networks:
      - gulinet
    ports:
      - "${HOST_IP}:${GULIMALL_WARE_PORT}:80"
#      - "${DEBUG_HOST_IP}:${GULIMALL_WARE_DEBUG_PORT}:5005"
  gulimall-member:
    image: gulimall-member:0.0.1-SNAPSHOT
    deploy:
      resources:
        limits:
          memory: "${APP_MEMORY_LIMIT}"
    container_name: gulimall-member
    environment:
      - "SERVICE_IGNORE=true"
      - "JAVA_TOOL_OPTIONS=${APP_JVM_FLAGS}"
    networks:
      - gulinet
    ports:
      - "${HOST_IP}:${GULIMALL_PRODUCT_PORT}:80"
#      - "${DEBUG_HOST_IP}:${GULIMALL_PRODUCT_DEBUG_PORT}:5005"
  gulimall-third-party:
    image: gulimall-third-party:0.0.1-SNAPSHOT
    deploy:
      resources:
        limits:
          memory: "${APP_MEMORY_LIMIT}"
    container_name: gulimall-third-party
    environment:
      - "SERVICE_IGNORE=true"
      - "JAVA_TOOL_OPTIONS=${APP_JVM_FLAGS}"
    networks:
      - gulinet
    ports:
      - "${HOST_IP}:${GULIMALL_THIRD_PARTY_PORT}:80"
#      - "${DEBUG_HOST_IP}:${GULIMALL_THIRD_PARTY_DEBUG_PORT}:5005"
  gulimall-search:
    image: gulimall-search:0.0.1-SNAPSHOT
    deploy:
      resources:
        limits:
          memory: "${APP_MEMORY_LIMIT}"
    container_name: gulimall-search
    environment:
      - "SERVICE_IGNORE=true"
      - "JAVA_TOOL_OPTIONS=${APP_JVM_FLAGS}"
    networks:
      - gulinet
    ports:
      - "${HOST_IP}:${GULIMALL_SEARCH_PORT}:80"
#      - "${DEBUG_HOST_IP}:${GULIMALL_SEARCH_DEBUG_PORT}:5005"
  gulimall-auth-server:
    image: gulimall-auth-server:0.0.1-SNAPSHOT
    deploy:
      resources:
        limits:
          memory: "${APP_MEMORY_LIMIT}"
    container_name: gulimall-auth-server
    environment:
      - "SERVICE_IGNORE=true"
      - "JAVA_TOOL_OPTIONS=${APP_JVM_FLAGS}"
    networks:
      - gulinet
    ports:
      - "${HOST_IP}:${GULIMALL_AUTH_SERVER_PORT}:80"
#      - "${DEBUG_HOST_IP}:${GULIMALL_AUTH_SERVER_DEBUG_PORT}:5005"
  gulimall-cart:
    image: gulimall-cart:0.0.1-SNAPSHOT
    deploy:
      resources:
        limits:
          memory: "${APP_MEMORY_LIMIT}"
    container_name: gulimall-cart
    environment:
      - "SERVICE_IGNORE=true"
      - "JAVA_TOOL_OPTIONS=${APP_JVM_FLAGS}"
    networks:
      - gulinet
    ports:
      - "${HOST_IP}:${GULIMALL_CART_PORT}:80"
#      - "${DEBUG_HOST_IP}:${GULIMALL_CART_DEBUG_PORT}:5005"
  gulimall-seckill:
    image: gulimall-seckill:0.0.1-SNAPSHOT
    deploy:
      resources:
        limits:
          memory: "${APP_MEMORY_LIMIT}"
    container_name: gulimall-seckill
    environment:
      - "SERVICE_IGNORE=true"
      - "JAVA_TOOL_OPTIONS=${APP_JVM_FLAGS}"
    networks:
      - gulinet
    ports:
      - "${HOST_IP}:${GULIMALL_SECKILL_PORT}:80"
#      - "${DEBUG_HOST_IP}:${GULIMALL_SECKILL_DEBUG_PORT}:5005"
  gulimall-gateway:
    image: gulimall-gateway:0.0.1-SNAPSHOT
    deploy:
      resources:
        limits:
          memory: "${APP_MEMORY_LIMIT}"
    container_name: gulimall-gateway
    environment:
      - "SERVICE_IGNORE=true"
      - "JAVA_TOOL_OPTIONS=${APP_JVM_FLAGS}"
    networks:
      - gulinet
    ports:
      - "${HOST_IP}:${GULIMALL_GATEWAY_PORT}:80"
#      - "${DEBUG_HOST_IP}:${GULIMALL_GATEWAY_DEBUG_PORT}:5005"

  renren-fast:
    image: renren-fast:3.0.0
    deploy:
      resources:
        limits:
          memory: "${APP_MEMORY_LIMIT}"
    container_name: renren-fast
    environment:
      - "SERVICE_IGNORE=true"
      - "JAVA_TOOL_OPTIONS=${APP_JVM_FLAGS}"
    networks:
      - gulinet
    ports:
      - "${HOST_IP}:${RENREN_FAST_PORT}:80"
  gulimall-admin-vue:
    build: ../../gulimall-admin-vue
    image: gulimall-admin-vue:0.0.1-SNAPSHOT
    deploy:
      restart_policy:
        condition: on-failure
        delay: 10s
      resources:
        limits:
          memory: "${APP_MEMORY_LIMIT}"
    container_name: gulimall-admin-vue
    networks:
      - gulinet
    ports:
      - "${HOST_IP}:${GULIMALL_ADMIN_VUE_PORT}:80"
