spring:
  cloud:
    alicloud:
      access-key: LTAI4G9eHMWwHtocdKQxyd9V
      secret-key: 2sxhchef7fTGAodaIj9cowFx4gCZl5
      oss:
        endpoint: oss-cn-shenzhen.aliyuncs.com
        bucket: proj1
      sms:
        host: "http://localhost:38300"
        path: "/api/thirdparty/sms/"
        sign: "1"
        skin: "1"
        appcode: "abc"

  application:
    name: gulimall-third-party

server:
  port: 38250
